import type { Metadata } from 'next';
import '@/styles/globals.css';
import { inter, notoSansJP } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'udemy-nextjs13-learning-with-microblog',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ja">
      <body
        className={`${inter.variable} ${notoSansJP.variable} font-sans antialiased bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
